version: "3.4"

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: 'rabbitmq'
    restart: always
    expose:
     - "15672"
     - "5672"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    volumes:
      - ./rabbitmq_data/:/var/lib/rabbitmq/
      - ./rabbitmq.sh:/usr/local/bin/rabbitmq.sh
    ulimits:
      nofile:
        soft: 500000
        hard: 1000000
    entrypoint: /usr/local/bin/rabbitmq.sh
