version: "3.4"

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: '023_rabbit'
    restart: always
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
      - /root/rabbitmq_data/:/var/lib/rabbitmq/mnesia/
